trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Synchronizing with GitHub...
  displayName: 'Sync with GitHub'

- checkout: self

- script: |
    git config --global user.email "princeghoghari9@gmail.com"
    git config --global user.name "prince3453"
    git remote add github https://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@github.com/prince3453/AIducation.git
    git push github cloning
  displayName: 'Push to GitHub'
