trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Synchronizing with GitHub...
  displayName: 'Sync with GitHub'

- checkout: self

- script: |
    echo "Configuring git user details..."
    git config --global user.email "princeghoghari9@gmail.com"
    git config --global user.name "prince3453"
    
    echo "Setting up remote..."
    git remote add github https://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@github.com/prince3453/AIducation.git

    echo "Committing and pushing changes..."
    git commit -m "update from Azure devops Synchronization"
    git push -u origin HEAD:main
  displayName: 'Push to GitHub'
